version: '3.8'
services:
  mongo:
    image: mongo:3.6-xenial
    container_name: mongo
    environment:
      ONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

    ports:
      - "27017:27017"
    volumes:
      - C:\docker-volume\mongo:/docker-entrypoint-initdb.d
networks:
  development-network:
    driver: bridge